# - name: Verificar todas as variáveis de host
#   debug:
#     var: hostvars['localhost']

# - name: Verificar todas as variáveis
#   debug:
#     var: hostvars

# - name: Verificar todas as variáveis de host
#   debug:
#     var: hostvars['K8S_TOKEN_HOLDER']

- name: Debug - Verificar o token e o hash do master no worker 
  debug:
    #msg: "[WORKER] K8S_TOKEN_HOLDER - O token é {{ hostvars[item].K8S_TOKEN_HOLDER }}, e o hash é {{ hostvars[item].K8S_CA_HASH }}"
    #msg: "[WORKER] K8S_TOKEN_HOLDER - O token é {{ hostvars[item].token }}, e o hash é {{ hostvars[item].hash }}"
    #msg: "[WORKER] K8S_TOKEN_HOLDER - O token é {{ hostvars[item][K8S_TOKEN_HOLDER].token }}, e o hash é {{ hostvars[item][K8S_TOKEN_HOLDER].hash }}"
    msg: "[WORKER] K8S_TOKEN_HOLDER - O token é {{ hostvars['K8S_TOKEN_HOLDER'].token }}, e o hash é {{ hostvars['K8S_TOKEN_HOLDER'].hash }}"
  #with_items: "{{ groups['master'] }}"

- name: Removendo o cluster
  command:
    kubeadm reset --force
  register: kubeadm_reset

- name: Adicionando o worker ao cluster k8s
  shell: 
    kubeadm join --token={{ hostvars['K8S_TOKEN_HOLDER'].token }} \
    --discovery-token-ca-cert-hash sha256:{{ hostvars['K8S_TOKEN_HOLDER'].hash }} \
    {{ K8S_MASTER_NODE_IP }}:{{ K8S_API_SECURE_PORT }}
  with_items: "{{ groups['master'] }}"